# Generated by Django 4.0.3 on 2022-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jsonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('trade_code', models.CharField(max_length=30)),
                ('high', models.CharField(max_length=10)),
                ('low', models.CharField(max_length=10)),
                ('open', models.CharField(max_length=10)),
                ('close', models.CharField(max_length=10)),
                ('volume', models.CharField(max_length=20)),
            ],
        ),
    ]
